#!/usr/bin/env bash

function _install {
    yum install -y $@
}

function _xen_repo_install {
    _install wget
    cd /etc/yum.repos.d/
    wget http://dev.centos.org/centos/6/xen-c6/xen-c6.repo
    yum repolist
    yum upgrade -y
}

function _xen_update_grub_conf {
    grub_conf=$(readlink -f /etc/grub.conf)
   
    set +e 
    if [ -n "`grep "title" -m 1 $grub_conf | grep "title xen" $grub_conf`" ]
    then
        echo "xen already first in grub.conf"
        return
    fi
    set -e

    old_grub_conf=/etc/grub.conf.old.`date "+%Y%m%d%H%M%S"`
    cp $grub_conf $old_grub_conf

    grub_old_options=$(grep "title" /etc/grub.conf -A 500)

    echo "# generated by xcp-devinstall" | cat > $grub_conf
    grep "title" $old_grub_conf -B 1000 -m 1 | grep -v title | cat >> $grub_conf

    dom0_mem=${dom0_mem:-"1024M"}
    kernel_version=$(rpm -q kernel | grep 3.4 -m 1 | sed "s/kernel-//")
    vg=$(lvm vgdisplay | grep Name | cut -c 25- )
    cat >> $grub_conf << EOF
title xen
        root (hd0,0)
        kernel /xen.gz dom0_mem=${dom0_mem},max:${dom0_mem} loglvl=all guest_loglvl=all
        module /vmlinuz-${kernel_version} ro root=/dev/mapper/${vg}-lv_root rd_NO_LUKS  KEYBOARDTYPE=pc KEYTABLE=uk LANG=en_US.UTF-8 rd_LVM_LV=${vg}/lv_root rd_NO_MD quiet SYSFONT=latarcyrheb-sun16 rhgb crashkernel=auto rd_NO_DM rd_LVM_LV=${vg}/lv_swap
        module /initramfs-${kernel_version}.img
EOF

    grep "title" $old_grub_conf -A 1000 | cat >> $grub_conf
}

function xen_install {
    _xen_repo_install
    _install kernel kernel-firmware
    _install xen
    _xen_update_grub_conf
}
